# Generated by Django 4.2.20 on 2025-04-06 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibicms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileportfolio',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profileportfolio',
            name='last_name',
        ),
    ]
