# Generated by Django 4.2.20 on 2025-04-06 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ibicms', '0002_remove_profileportfolio_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('project_text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='newsletter_images/')),
                ('head_color', models.CharField(default='#000000', max_length=7)),
                ('body_color', models.CharField(default='#ffffff', max_length=7)),
                ('footer_color', models.CharField(default='#343a40', max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
