# Generated by Django 4.2.20 on 2025-04-24 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibicms', '0003_profilenewsletter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilenewsletter',
            old_name='subtitle',
            new_name='content',
        ),
    ]
