# Generated by Django 4.2.20 on 2025-04-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibicms', '0004_rename_subtitle_profilenewsletter_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilenewsletter',
            name='body_color',
        ),
        migrations.RemoveField(
            model_name='profilenewsletter',
            name='project_text',
        ),
        migrations.AlterField(
            model_name='profilenewsletter',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
